#!/usr/bin/env python3
"""Embed Live2D bear assets as base64 for file:// protocol (no fetch)."""

from __future__ import annotations

import base64
import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BEAR = ROOT / "site" / "static" / "live2d" / "bear"
OUT = ROOT / "site" / "js" / "live2d-inline.js"

FILES = {
    "model.moc3": BEAR / "model.moc3",
    "model.physics3.json": BEAR / "model.physics3.json",
    "textures/texture_00.png": BEAR / "textures" / "texture_00.png",
    "expressions/nowatermark.exp3.json": BEAR / "expressions" / "nowatermark.exp3.json",
}


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def main() -> None:
    settings_path = BEAR / "model.model3.json"
    if not settings_path.exists():
        raise SystemExit(f"Missing {settings_path}")

    settings = json.loads(settings_path.read_text(encoding="utf-8"))
    files: dict[str, str] = {}
    for key, path in FILES.items():
        if not path.exists():
            raise SystemExit(f"Missing Live2D asset: {path}")
        files[key] = b64(path)
        print(f"Embedded {key} ({path.stat().st_size // 1024} KB)")

    payload = {
        "generatedAt": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "settings": settings,
        "files": files,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False)
    OUT.write_text(
        "/** Auto-generated by sync/build-live2d-inline.py — do not edit */\n"
        f"export const LIVE2D_INLINE = {body};\n\n"
        "export function getLive2DInlineBundle() {\n"
        "  return LIVE2D_INLINE;\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
