#!/usr/bin/env python3
"""Embed static/music audio as base64 for file:// (double-click index.html)."""

from __future__ import annotations

import base64
import json
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MUSIC_DIR = ROOT / "site" / "static" / "music"
PLAYLIST_FILE = MUSIC_DIR / "playlist.json"
OUT = ROOT / "site" / "js" / "music-inline.js"

AUDIO_EXT = {".mp3", ".ogg", ".wav", ".flac", ".m4a", ".aac", ".opus"}


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def read_playlist() -> dict:
    if not PLAYLIST_FILE.exists():
        return {"tracks": []}
    try:
        return json.loads(PLAYLIST_FILE.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {"tracks": []}


def main() -> None:
    playlist = read_playlist()
    files: dict[str, str] = {}

    for track in playlist.get("tracks", []):
        file_name = track.get("file")
        if not file_name:
            continue
        path = MUSIC_DIR / file_name
        if not path.exists():
            print(f"Skip missing audio: {path}")
            continue
        if path.suffix.lower() not in AUDIO_EXT:
            continue
        files[file_name] = b64(path)
        print(f"Embedded {file_name} ({path.stat().st_size // 1024} KB)")

    payload = {
        "generatedAt": datetime.now().strftime("%Y-%m-%dT%H:%M:%S"),
        "files": files,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    body = json.dumps(payload, ensure_ascii=False)
    OUT.write_text(
        "/** Auto-generated by sync/build-music-inline.py — do not edit */\n"
        f"export const MUSIC_INLINE = {body};\n\n"
        "export function getMusicInlineFiles() {\n"
        "  return MUSIC_INLINE.files ?? {};\n"
        "}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size // 1024} KB, {len(files)} track(s))")


if __name__ == "__main__":
    main()
